
* Hebdomon - A LaTeX Class for Report Writing


** Table of Contents :TOC_5:
- [[#hebdomon---a-latex-class-for-report-writing][Hebdomon - A LaTeX Class for Report Writing]]
  - [[#introduction][Introduction]]
    - [[#adding-custom-commands][Adding Custom Commands]]

** Introduction

Hebdomon is a latex documentclass for streamlining document creation in
latex.

Currently it supports minted out of the box.

The following packages are loaded for all OPTIONS

The document uses [[https://fonts.google.com/specimen/Fira+Sans][FiraSans]] for as fontstyle.

| PACKAGE    | DEFINITION                                             |
|------------+--------------------------------------------------------|
| ~minted~     | For use in code presentation (requires python)         |
| ~nicematrix~ | For presenting matrices and tables in a cleaner syntax |
| ~graphicx~   | Inserting images into the document                     |

*** Adding Custom Commands

While it is up to the user to add whatever they wish, to keep track all of
the custom stuff it is recommend to put it in a position such as follows:

#+begin_src latex
%--CUSTOM-COMMANDS---------------------------------------------------------
\newcommand{...}
\renewcommnad{...}
\def\lorem
%--------------------------------------------------------------------------
#+end_src

This would allow you to easily keep all of them organised.

Then what do I know, I am just a README file.
